### ISSUE TITLE
README - USER

### ISSUE THREAD

**Issue by ThomasP-MTL** [ThomasP-MTL/spotifree-grp2#11]
faire le read me a destination de l utilsateur qui utilisera Spotifree

1- creer un dossier Spotifree dans un repertoire personnel. Ce fichier servira a la fois pour placer les fichiers de configurations (si requis, ex clé RSA) et servira egalement de lieux de dépot des musiques ecoutées. 
2 - lancer le programme spotifree.py
3- entrer un nom d utilisateur et un mot de passe .....

**Comment by beckguillaume** [comment]
readme écrit
